baseURL = "https://stickeroperation.center/"
languageCode = "en-us"
title = "Sticker Operation Center"
theme = "minimo"
pagination.pagerSize = 10

preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Federating Stickerboxes since 36C3"
title404 = "Nothingâ€™s here!"

[params.assets]
favicon = "favicon-rainbow.png"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "2006-01-02"
hideEntryNavigation = true # boolean / array of sections
hideEntryMeta = true # boolean / array of sections
showReadingTime = false
showLastmod = false
taxonomyCloudShuffle = false
accentColor = "#6800e7"
hideMainMenu = true

[params.sidebar]
enable = true

[params.widgets]
header = []
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu"]
footer = ["social_menu"]

[params.social]
email = "exchange@stickeroperation.center"
twitter = "c3stoc"
mastodon = "@c3stoc@chaos.social"
mastodonUrl = "https://chaos.social/@c3stoc"

[params.comments]
enable = false

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

#[[menu.main]]
#name = "Repo"
#weight = -10
#identifier = "repository"
#url = "https://github.com/MunifTanjim/minimo"

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.en]
languageName = "English"
weight = 1

